plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = rootProject.mod_version
group = "${rootProject.mod_group_id}.compat"

base {
    archivesName = 'x3d_map_compat_smu'
}

repositories {
    mavenLocal()
    maven {
        url = "https://maven.blamejared.com"
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = rootProject.neo_version
    runs {
//        client {
//            client()
//            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
//            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
//        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    mods {
        x3d_map_compat_smu {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation project(':')
    compileOnly "com.xkball:xklib-3d:${rootProject.xklib_version}"
    compileOnly "com.xkball:xklib-ap:${rootProject.xklib_version}"
    compileOnly "com.xkball:xklib-mc:${rootProject.xklib_version}"
    compileOnly "com.xkball:xklib-ui:${rootProject.xklib_version}"
    implementation files('libs/SignMeUp-NeoForge-26.1-1.1.2.jar')
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version      : rootProject.minecraft_version,
            minecraft_version_range: rootProject.minecraft_version_range,
            neo_version            : rootProject.neo_version,
            mod_license            : rootProject.mod_license,
            mod_version            : rootProject.mod_version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar') {
    exclude 'assets/exhibition_portal/**'
    exclude 'data/exhibition_portal/**'
}
